package com.totaplay.searchONT.tprovisioningSoa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-14T19:56:28.557-06:00
 * Generated source version: 3.5.0
 *
 */
@WebServiceClient(name = "TProvisioning",
                  wsdlLocation = "http://10.213.8.248/TPESOASF/TProvisioning.asmx?wsdl",
                  targetNamespace = "http://tempuri.org/")
public class TProvisioning extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "TProvisioning");
    public final static QName TProvisioningSoap12 = new QName("http://tempuri.org/", "TProvisioningSoap12");
    public final static QName TProvisioningSoap = new QName("http://tempuri.org/", "TProvisioningSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://10.213.8.248/TPESOASF/TProvisioning.asmx?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TProvisioning.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.213.8.248/TPESOASF/TProvisioning.asmx?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TProvisioning(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TProvisioning(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TProvisioning() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TProvisioning(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TProvisioning(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TProvisioning(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns TProvisioningSoap
     */
    @WebEndpoint(name = "TProvisioningSoap12")
    public TProvisioningSoap getTProvisioningSoap12() {
        return super.getPort(TProvisioningSoap12, TProvisioningSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TProvisioningSoap
     */
    @WebEndpoint(name = "TProvisioningSoap12")
    public TProvisioningSoap getTProvisioningSoap12(WebServiceFeature... features) {
        return super.getPort(TProvisioningSoap12, TProvisioningSoap.class, features);
    }


    /**
     *
     * @return
     *     returns TProvisioningSoap
     */
    @WebEndpoint(name = "TProvisioningSoap")
    public TProvisioningSoap getTProvisioningSoap() {
        return super.getPort(TProvisioningSoap, TProvisioningSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TProvisioningSoap
     */
    @WebEndpoint(name = "TProvisioningSoap")
    public TProvisioningSoap getTProvisioningSoap(WebServiceFeature... features) {
        return super.getPort(TProvisioningSoap, TProvisioningSoap.class, features);
    }

}
