package com.totaplay.searchONT.tprovisioningSoa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-14T19:56:28.539-06:00
 * Generated source version: 3.5.0
 *
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "TProvisioningSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface TProvisioningSoap {

    @WebMethod(operationName = "GetModels", action = "http://tempuri.org/GetModels")
    @RequestWrapper(localName = "GetModels", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetModels")
    @ResponseWrapper(localName = "GetModelsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetModelsResponse")
    @WebResult(name = "GetModelsResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetcatalog getModels();

    @WebMethod(operationName = "QuitRoutingIPTV", action = "http://tempuri.org/QuitRoutingIPTV")
    @RequestWrapper(localName = "QuitRoutingIPTV", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QuitRoutingIPTV")
    @ResponseWrapper(localName = "QuitRoutingIPTVResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QuitRoutingIPTVResponse")
    @WebResult(name = "QuitRoutingIPTVResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult quitRoutingIPTV(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "strOLTName", targetNamespace = "http://tempuri.org/")
        java.lang.String strOLTName,
        @WebParam(name = "CustomerId", targetNamespace = "http://tempuri.org/")
        java.lang.String customerId,
        @WebParam(name = "strName", targetNamespace = "http://tempuri.org/")
        java.lang.String strName,
        @WebParam(name = "strSNONT", targetNamespace = "http://tempuri.org/")
        java.lang.String strSNONT,
        @WebParam(name = "strFrame", targetNamespace = "http://tempuri.org/")
        java.lang.String strFrame,
        @WebParam(name = "strSlot", targetNamespace = "http://tempuri.org/")
        java.lang.String strSlot,
        @WebParam(name = "strPort", targetNamespace = "http://tempuri.org/")
        java.lang.String strPort,
        @WebParam(name = "strONTID", targetNamespace = "http://tempuri.org/")
        java.lang.String strONTID,
        @WebParam(name = "strModeInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strModeInvoke,
        @WebParam(name = "LngUserId", targetNamespace = "http://tempuri.org/")
        long lngUserId,
        @WebParam(name = "strIpInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strIpInvoke,
        @WebParam(name = "blnGuiNew", targetNamespace = "http://tempuri.org/")
        boolean blnGuiNew,
        @WebParam(name = "STRDN", targetNamespace = "http://tempuri.org/")
        java.lang.String strdn
    );

    @WebMethod(operationName = "GetRegionByOLT", action = "http://tempuri.org/GetRegionByOLT")
    @RequestWrapper(localName = "GetRegionByOLT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegionByOLT")
    @ResponseWrapper(localName = "GetRegionByOLTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetRegionByOLTResponse")
    @WebResult(name = "GetRegionByOLTResult", targetNamespace = "http://tempuri.org/")
    public int getRegionByOLT(

        @WebParam(name = "OLT", targetNamespace = "http://tempuri.org/")
        java.lang.String olt
    );

    @WebMethod(operationName = "GetAutoFindTL1bySNsf", action = "http://tempuri.org/GetAutoFindTL1bySNsf")
    @RequestWrapper(localName = "GetAutoFindTL1bySNsf", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAutoFindTL1BySNsf")
    @ResponseWrapper(localName = "GetAutoFindTL1bySNsfResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAutoFindTL1BySNsfResponse")
    @WebResult(name = "GetAutoFindTL1bySNsfResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.AutofindONT getAutoFindTL1BySNsf(

        @WebParam(name = "strSerialNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String strSerialNumber,
        @WebParam(name = "strUser", targetNamespace = "http://tempuri.org/")
        java.lang.String strUser,
        @WebParam(name = "strPWD", targetNamespace = "http://tempuri.org/")
        java.lang.String strPWD
    );

    @WebMethod(operationName = "Suppression", action = "http://tempuri.org/Suppression")
    @RequestWrapper(localName = "Suppression", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Suppression")
    @ResponseWrapper(localName = "SuppressionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SuppressionResponse")
    @WebResult(name = "SuppressionResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult suppression(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "arrActivation", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrActivation arrActivation,
        @WebParam(name = "idPackage", targetNamespace = "http://tempuri.org/")
        long idPackage,
        @WebParam(name = "idCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String idCustomer,
        @WebParam(name = "CustomerAlias", targetNamespace = "http://tempuri.org/")
        java.lang.String customerAlias,
        @WebParam(name = "InVoIPs", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP inVoIPs,
        @WebParam(name = "InIPTVs", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV inIPTVs,
        @WebParam(name = "strDnMaster", targetNamespace = "http://tempuri.org/")
        java.lang.String strDnMaster,
        @WebParam(name = "PeriodHrs", targetNamespace = "http://tempuri.org/")
        java.lang.String periodHrs,
        @WebParam(name = "dteLimit", targetNamespace = "http://tempuri.org/")
        javax.xml.datatype.XMLGregorianCalendar dteLimit,
        @WebParam(name = "intReason", targetNamespace = "http://tempuri.org/")
        int intReason,
        @WebParam(name = "strComments", targetNamespace = "http://tempuri.org/")
        java.lang.String strComments,
        @WebParam(name = "strIdUserEvergent", targetNamespace = "http://tempuri.org/")
        java.lang.String strIdUserEvergent
    );

    @WebMethod(operationName = "GetSearchONT_Dash", action = "http://tempuri.org/GetSearchONT_Dash")
    @RequestWrapper(localName = "GetSearchONT_Dash", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSearchONTDash")
    @ResponseWrapper(localName = "GetSearchONT_DashResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSearchONTDashResponse")
    @WebResult(name = "GetSearchONT_DashResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetONT getSearchONTDash(

        @WebParam(name = "strvalue", targetNamespace = "http://tempuri.org/")
        java.lang.String strvalue
    );

    @WebMethod(operationName = "GetOLTVendor", action = "http://tempuri.org/GetOLTVendor")
    @RequestWrapper(localName = "GetOLTVendor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOLTVendor")
    @ResponseWrapper(localName = "GetOLTVendorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOLTVendorResponse")
    @WebResult(name = "GetOLTVendorResult", targetNamespace = "http://tempuri.org/")
    public int getOLTVendor(

        @WebParam(name = "OLTName", targetNamespace = "http://tempuri.org/")
        java.lang.String oltName
    );

    @WebMethod(operationName = "CancelONTU200", action = "http://tempuri.org/CancelONTU200")
    @RequestWrapper(localName = "CancelONTU200", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelONTU200")
    @ResponseWrapper(localName = "CancelONTU200Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CancelONTU200Response")
    @WebResult(name = "CancelONTU200Result", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult cancelONTU200(

        @WebParam(name = "filter", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.FilterOLTS filter,
        @WebParam(name = "strModeInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strModeInvoke,
        @WebParam(name = "LngUserId", targetNamespace = "http://tempuri.org/")
        long lngUserId,
        @WebParam(name = "strIpInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strIpInvoke,
        @WebParam(name = "blnGuiNew", targetNamespace = "http://tempuri.org/")
        boolean blnGuiNew
    );

    @WebMethod(operationName = "PackageActivationEnlaceFusion", action = "http://tempuri.org/PackageActivationEnlaceFusion")
    @RequestWrapper(localName = "PackageActivationEnlaceFusion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageActivationEnlaceFusion")
    @ResponseWrapper(localName = "PackageActivationEnlaceFusionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageActivationEnlaceFusionResponse")
    @WebResult(name = "PackageActivationEnlaceFusionResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult packageActivationEnlaceFusion(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "arrActivation", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrActivation arrActivation,
        @WebParam(name = "idPackage", targetNamespace = "http://tempuri.org/")
        long idPackage,
        @WebParam(name = "idCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String idCustomer,
        @WebParam(name = "CustomerAlias", targetNamespace = "http://tempuri.org/")
        java.lang.String customerAlias,
        @WebParam(name = "AddInHSFI", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI addInHSFI,
        @WebParam(name = "arrAddInVoIP", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP arrAddInVoIP,
        @WebParam(name = "arrAddInVoIPTroncal", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP arrAddInVoIPTroncal,
        @WebParam(name = "ArrIPStatic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic arrIPStatic,
        @WebParam(name = "ArrIPDynamic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic arrIPDynamic,
        @WebParam(name = "lngIDaddIP", targetNamespace = "http://tempuri.org/")
        long lngIDaddIP,
        @WebParam(name = "intcounttroncal", targetNamespace = "http://tempuri.org/")
        int intcounttroncal,
        @WebParam(name = "strparamIPsStatic", targetNamespace = "http://tempuri.org/")
        java.lang.String strparamIPsStatic,
        @WebParam(name = "strCCTV", targetNamespace = "http://tempuri.org/")
        java.lang.String strCCTV,
        @WebParam(name = "ArrIPStaticCCTV", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPStaticCCTV arrIPStaticCCTV,
        @WebParam(name = "intEncoderTV", targetNamespace = "http://tempuri.org/")
        int intEncoderTV,
        @WebParam(name = "intCountCCTV", targetNamespace = "http://tempuri.org/")
        int intCountCCTV
    );

    @WebMethod(operationName = "DeleteActivation", action = "http://tempuri.org/DeleteActivation")
    @RequestWrapper(localName = "DeleteActivation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteActivation")
    @ResponseWrapper(localName = "DeleteActivationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteActivationResponse")
    @WebResult(name = "DeleteActivationResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult deleteActivation(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "idCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String idCustomer,
        @WebParam(name = "arrActivation", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ModelGetONT arrActivation,
        @WebParam(name = "arrVoIP", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP arrVoIP,
        @WebParam(name = "arrIPTV", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV arrIPTV,
        @WebParam(name = "strDnMaster", targetNamespace = "http://tempuri.org/")
        java.lang.String strDnMaster
    );

    @WebMethod(operationName = "Upgrade", action = "http://tempuri.org/Upgrade")
    @RequestWrapper(localName = "Upgrade", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Upgrade")
    @ResponseWrapper(localName = "UpgradeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpgradeResponse")
    @WebResult(name = "UpgradeResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult upgrade(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "deleteActivation", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.DtoDeleteActivation deleteActivation,
        @WebParam(name = "PackageActivation", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.DtoPackageActivation packageActivation
    );

    @WebMethod(operationName = "TestONT", action = "http://tempuri.org/TestONT")
    @RequestWrapper(localName = "TestONT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TestONT")
    @ResponseWrapper(localName = "TestONTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.TestONTResponse")
    @WebResult(name = "TestONTResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult testONT(

        @WebParam(name = "strOLT", targetNamespace = "http://tempuri.org/")
        java.lang.String strOLT,
        @WebParam(name = "strFrame", targetNamespace = "http://tempuri.org/")
        java.lang.String strFrame,
        @WebParam(name = "strSlot", targetNamespace = "http://tempuri.org/")
        java.lang.String strSlot,
        @WebParam(name = "strPort", targetNamespace = "http://tempuri.org/")
        java.lang.String strPort,
        @WebParam(name = "strONTID", targetNamespace = "http://tempuri.org/")
        java.lang.String strONTID,
        @WebParam(name = "strserialnumber", targetNamespace = "http://tempuri.org/")
        java.lang.String strserialnumber,
        @WebParam(name = "idCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String idCustomer,
        @WebParam(name = "LngUserId", targetNamespace = "http://tempuri.org/")
        long lngUserId,
        @WebParam(name = "strIpInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strIpInvoke,
        @WebParam(name = "strModeInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strModeInvoke
    );

    @WebMethod(operationName = "ProcesaAct_Horario", action = "http://tempuri.org/ProcesaAct_Horario")
    @RequestWrapper(localName = "ProcesaAct_Horario", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcesaActHorario")
    @ResponseWrapper(localName = "ProcesaAct_HorarioResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ProcesaActHorarioResponse")
    public void procesaActHorario(

        @WebParam(name = "cuenta", targetNamespace = "http://tempuri.org/")
        java.lang.String cuenta
    );

    @WebMethod(operationName = "GetAlarms", action = "http://tempuri.org/GetAlarms")
    @RequestWrapper(localName = "GetAlarms", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAlarms")
    @ResponseWrapper(localName = "GetAlarmsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAlarmsResponse")
    @WebResult(name = "GetAlarmsResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrayOfGetALarm getAlarms(

        @WebParam(name = "LstrSN", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfString lstrSN
    );

    @WebMethod(operationName = "ReAprov_Onts_Red", action = "http://tempuri.org/ReAprov_Onts_Red")
    @RequestWrapper(localName = "ReAprov_Onts_Red", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReAprovOntsRed")
    @ResponseWrapper(localName = "ReAprov_Onts_RedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReAprovOntsRedResponse")
    public void reAprovOntsRed()
;

    @WebMethod(operationName = "CreateUserAAA_Masivo", action = "http://tempuri.org/CreateUserAAA_Masivo")
    @RequestWrapper(localName = "CreateUserAAA_Masivo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateUserAAAMasivo")
    @ResponseWrapper(localName = "CreateUserAAA_MasivoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateUserAAAMasivoResponse")
    public void createUserAAAMasivo()
;

    @WebMethod(action = "http://tempuri.org/getNetworkInformation")
    @RequestWrapper(localName = "getNetworkInformation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetNetworkInformation")
    @ResponseWrapper(localName = "getNetworkInformationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetNetworkInformationResponse")
    @WebResult(name = "getNetworkInformationResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrNetwork getNetworkInformation(

        @WebParam(name = "strSerialNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String strSerialNumber
    );

    @WebMethod(operationName = "DeleteDN", action = "http://tempuri.org/DeleteDN")
    @RequestWrapper(localName = "DeleteDN", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteDN")
    @ResponseWrapper(localName = "DeleteDNResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteDNResponse")
    @WebResult(name = "DeleteDNResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult deleteDN(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "strOLTName", targetNamespace = "http://tempuri.org/")
        java.lang.String strOLTName,
        @WebParam(name = "CustomerId", targetNamespace = "http://tempuri.org/")
        java.lang.String customerId,
        @WebParam(name = "strName", targetNamespace = "http://tempuri.org/")
        java.lang.String strName,
        @WebParam(name = "strSNONT", targetNamespace = "http://tempuri.org/")
        java.lang.String strSNONT,
        @WebParam(name = "strFrame", targetNamespace = "http://tempuri.org/")
        java.lang.String strFrame,
        @WebParam(name = "strSlot", targetNamespace = "http://tempuri.org/")
        java.lang.String strSlot,
        @WebParam(name = "strPort", targetNamespace = "http://tempuri.org/")
        java.lang.String strPort,
        @WebParam(name = "strONTID", targetNamespace = "http://tempuri.org/")
        java.lang.String strONTID,
        @WebParam(name = "strModeInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strModeInvoke,
        @WebParam(name = "LngUserId", targetNamespace = "http://tempuri.org/")
        long lngUserId,
        @WebParam(name = "strIpInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strIpInvoke,
        @WebParam(name = "blnGuiNew", targetNamespace = "http://tempuri.org/")
        boolean blnGuiNew,
        @WebParam(name = "STRDN", targetNamespace = "http://tempuri.org/")
        java.lang.String strdn
    );

    @WebMethod(operationName = "ReAprov_Onts_RedSN", action = "http://tempuri.org/ReAprov_Onts_RedSN")
    @RequestWrapper(localName = "ReAprov_Onts_RedSN", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReAprovOntsRedSN")
    @ResponseWrapper(localName = "ReAprov_Onts_RedSNResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReAprovOntsRedSNResponse")
    public void reAprovOntsRedSN()
;

    @WebMethod(operationName = "GetSearchONT", action = "http://tempuri.org/GetSearchONT")
    @RequestWrapper(localName = "GetSearchONT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSearchONT")
    @ResponseWrapper(localName = "GetSearchONTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetSearchONTResponse")
    @WebResult(name = "GetSearchONTResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetONT getSearchONT(

        @WebParam(name = "strvalue", targetNamespace = "http://tempuri.org/")
        java.lang.String strvalue
    );

    /**
     * Get information from the ONT connection 
     */
    @WebMethod(operationName = "GetAutoFind", action = "http://tempuri.org/GetAutoFind")
    @RequestWrapper(localName = "GetAutoFind", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAutoFind")
    @ResponseWrapper(localName = "GetAutoFindResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetAutoFindResponse")
    @WebResult(name = "GetAutoFindResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrAutoFind getAutoFind(

        @WebParam(name = "strSerialNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String strSerialNumber
    );

    @WebMethod(operationName = "GetIP_TR069", action = "http://tempuri.org/GetIP_TR069")
    @RequestWrapper(localName = "GetIP_TR069", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIPTR069")
    @ResponseWrapper(localName = "GetIP_TR069Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIPTR069Response")
    @WebResult(name = "GetIP_TR069Result", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrWANIP getIPTR069(

        @WebParam(name = "strSN", targetNamespace = "http://tempuri.org/")
        java.lang.String strSN
    );

    @WebMethod(action = "http://tempuri.org/validAddDrmCustomerProfileFusion")
    @RequestWrapper(localName = "validAddDrmCustomerProfileFusion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidAddDrmCustomerProfileFusion")
    @ResponseWrapper(localName = "validAddDrmCustomerProfileFusionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidAddDrmCustomerProfileFusionResponse")
    @WebResult(name = "validAddDrmCustomerProfileFusionResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ModelValidReturn validAddDrmCustomerProfileFusion(

        @WebParam(name = "ArrBrm", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrBrm arrBrm,
        @WebParam(name = "arrActivation", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrActivation arrActivation,
        @WebParam(name = "lngIdPackage", targetNamespace = "http://tempuri.org/")
        long lngIdPackage,
        @WebParam(name = "strIdCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String strIdCustomer,
        @WebParam(name = "strCustomerAlias", targetNamespace = "http://tempuri.org/")
        java.lang.String strCustomerAlias,
        @WebParam(name = "arrAddOnVoIP", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP arrAddOnVoIP,
        @WebParam(name = "ArrAddon", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddons arrAddon,
        @WebParam(name = "intCountVoip", targetNamespace = "http://tempuri.org/")
        int intCountVoip,
        @WebParam(name = "strDown", targetNamespace = "http://tempuri.org/")
        int strDown,
        @WebParam(name = "strUp", targetNamespace = "http://tempuri.org/")
        int strUp,
        @WebParam(name = "intCountHSI", targetNamespace = "http://tempuri.org/")
        int intCountHSI,
        @WebParam(name = "strTypeInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strTypeInvoke,
        @WebParam(name = "intCountTV", targetNamespace = "http://tempuri.org/")
        int intCountTV,
        @WebParam(name = "idCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String idCustomer,
        @WebParam(name = "arrAddOnIptv", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV arrAddOnIptv,
        @WebParam(name = "AddInHSFI", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI addInHSFI,
        @WebParam(name = "ArrIPStatic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic arrIPStatic,
        @WebParam(name = "ArrIPDynamic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic arrIPDynamic,
        @WebParam(name = "mdlBscsQry", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.MdlBscQry mdlBscsQry,
        @WebParam(name = "ONTCON", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrRoutingHSI ontcon,
        @WebParam(name = "blnExistONT", targetNamespace = "http://tempuri.org/")
        boolean blnExistONT,
        @WebParam(name = "mdlgenerals", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.MdlGeneralsSystem mdlgenerals,
        @WebParam(name = "blnConect", targetNamespace = "http://tempuri.org/")
        boolean blnConect,
        @WebParam(name = "srrfing", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAutoFind srrfing,
        @WebParam(name = "strVersion", targetNamespace = "http://tempuri.org/")
        java.lang.String strVersion,
        @WebParam(name = "mdlPOrts", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ModelGetModelPorts mdlPOrts,
        @WebParam(name = "blnGaoke", targetNamespace = "http://tempuri.org/")
        boolean blnGaoke,
        @WebParam(name = "strModel", targetNamespace = "http://tempuri.org/")
        java.lang.String strModel
    );

    @WebMethod(operationName = "ReconectaDns", action = "http://tempuri.org/ReconectaDns")
    @RequestWrapper(localName = "ReconectaDns", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReconectaDns")
    @ResponseWrapper(localName = "ReconectaDnsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReconectaDnsResponse")
    public void reconectaDns()
;

    @WebMethod(operationName = "SetAdon", action = "http://tempuri.org/SetAdon")
    @RequestWrapper(localName = "SetAdon", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetAdon")
    @ResponseWrapper(localName = "SetAdonResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SetAdonResponse")
    @WebResult(name = "SetAdonResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult setAdon(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "arrONT", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrActivation arrONT,
        @WebParam(name = "ArrAddon", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddons arrAddon,
        @WebParam(name = "ArrIPStatic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic arrIPStatic
    );

    @WebMethod(action = "http://tempuri.org/getOpticalONT")
    @RequestWrapper(localName = "getOpticalONT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOpticalONT")
    @ResponseWrapper(localName = "getOpticalONTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOpticalONTResponse")
    @WebResult(name = "getOpticalONTResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.OntOptical getOpticalONT(

        @WebParam(name = "strOLTName", targetNamespace = "http://tempuri.org/")
        java.lang.String strOLTName,
        @WebParam(name = "strFrame", targetNamespace = "http://tempuri.org/")
        java.lang.String strFrame,
        @WebParam(name = "strSlot", targetNamespace = "http://tempuri.org/")
        java.lang.String strSlot,
        @WebParam(name = "strPort", targetNamespace = "http://tempuri.org/")
        java.lang.String strPort,
        @WebParam(name = "strONTID", targetNamespace = "http://tempuri.org/")
        java.lang.String strONTID,
        @WebParam(name = "User", targetNamespace = "http://tempuri.org/")
        java.lang.String user
    );

    @WebMethod(operationName = "ReAprov_Onts_Red3", action = "http://tempuri.org/ReAprov_Onts_Red3")
    @RequestWrapper(localName = "ReAprov_Onts_Red3", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReAprovOntsRed3")
    @ResponseWrapper(localName = "ReAprov_Onts_Red3Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReAprovOntsRed3Response")
    public void reAprovOntsRed3()
;

    @WebMethod(operationName = "ChangeONT", action = "http://tempuri.org/ChangeONT")
    @RequestWrapper(localName = "ChangeONT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeONT")
    @ResponseWrapper(localName = "ChangeONTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeONTResponse")
    @WebResult(name = "ChangeONTResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult changeONT(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "CustomerId", targetNamespace = "http://tempuri.org/")
        java.lang.String customerId,
        @WebParam(name = "NewSerialONT", targetNamespace = "http://tempuri.org/")
        java.lang.String newSerialONT,
        @WebParam(name = "IdModel", targetNamespace = "http://tempuri.org/")
        long idModel,
        @WebParam(name = "strOldSerialNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String strOldSerialNumber
    );

    @WebMethod(operationName = "ReAprov_Onts_Red2", action = "http://tempuri.org/ReAprov_Onts_Red2")
    @RequestWrapper(localName = "ReAprov_Onts_Red2", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReAprovOntsRed2")
    @ResponseWrapper(localName = "ReAprov_Onts_Red2Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReAprovOntsRed2Response")
    public void reAprovOntsRed2()
;

    @WebMethod(operationName = "Update_ATA", action = "http://tempuri.org/Update_ATA")
    @RequestWrapper(localName = "Update_ATA", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateATA")
    @ResponseWrapper(localName = "Update_ATAResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateATAResponse")
    @WebResult(name = "Update_ATAResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult updateATA(

        @WebParam(name = "cuenta", targetNamespace = "http://tempuri.org/")
        java.lang.String cuenta,
        @WebParam(name = "DN", targetNamespace = "http://tempuri.org/")
        java.lang.String dn,
        @WebParam(name = "POT", targetNamespace = "http://tempuri.org/")
        java.lang.String pot
    );

    @WebMethod(operationName = "GetListTmCodeTWO", action = "http://tempuri.org/GetListTmCodeTWO")
    @RequestWrapper(localName = "GetListTmCodeTWO", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetListTmCodeTWO")
    @ResponseWrapper(localName = "GetListTmCodeTWOResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetListTmCodeTWOResponse")
    @WebResult(name = "GetListTmCodeTWOResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrayOfString getListTmCodeTWO();

    @WebMethod(operationName = "ReAprov_Onts_Red4", action = "http://tempuri.org/ReAprov_Onts_Red4")
    @RequestWrapper(localName = "ReAprov_Onts_Red4", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReAprovOntsRed4")
    @ResponseWrapper(localName = "ReAprov_Onts_Red4Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReAprovOntsRed4Response")
    public void reAprovOntsRed4()
;

    @WebMethod(action = "http://tempuri.org/validAddDrmCustomerProfileFusionEnlace")
    @RequestWrapper(localName = "validAddDrmCustomerProfileFusionEnlace", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidAddDrmCustomerProfileFusionEnlace")
    @ResponseWrapper(localName = "validAddDrmCustomerProfileFusionEnlaceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidAddDrmCustomerProfileFusionEnlaceResponse")
    @WebResult(name = "validAddDrmCustomerProfileFusionEnlaceResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ModelValidReturn validAddDrmCustomerProfileFusionEnlace(

        @WebParam(name = "arrActivation", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrActivation arrActivation,
        @WebParam(name = "lngIdPackage", targetNamespace = "http://tempuri.org/")
        long lngIdPackage,
        @WebParam(name = "strIdCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String strIdCustomer,
        @WebParam(name = "strCustomerAlias", targetNamespace = "http://tempuri.org/")
        java.lang.String strCustomerAlias,
        @WebParam(name = "arrAddOnVoIP", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP arrAddOnVoIP,
        @WebParam(name = "strTypeInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strTypeInvoke,
        @WebParam(name = "AddInHSFI", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI addInHSFI,
        @WebParam(name = "ArrIPStatic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic arrIPStatic,
        @WebParam(name = "ArrIPDynamic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic arrIPDynamic,
        @WebParam(name = "intcounttroncal", targetNamespace = "http://tempuri.org/")
        int intcounttroncal,
        @WebParam(name = "ArrIPStaticCCTV", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPStaticCCTV arrIPStaticCCTV
    );

    @WebMethod(operationName = "ChangeVoip", action = "http://tempuri.org/ChangeVoip")
    @RequestWrapper(localName = "ChangeVoip", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeVoip")
    @ResponseWrapper(localName = "ChangeVoipResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeVoipResponse")
    @WebResult(name = "ChangeVoipResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult changeVoip(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "CustomerId", targetNamespace = "http://tempuri.org/")
        java.lang.String customerId,
        @WebParam(name = "strSerialNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String strSerialNumber,
        @WebParam(name = "strNewDN", targetNamespace = "http://tempuri.org/")
        java.lang.String strNewDN,
        @WebParam(name = "strOldDN", targetNamespace = "http://tempuri.org/")
        java.lang.String strOldDN,
        @WebParam(name = "blnMaster", targetNamespace = "http://tempuri.org/")
        boolean blnMaster
    );

    @WebMethod(operationName = "GetModelChangePlan", action = "http://tempuri.org/GetModelChangePlan")
    @RequestWrapper(localName = "GetModelChangePlan", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetModelChangePlan")
    @ResponseWrapper(localName = "GetModelChangePlanResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetModelChangePlanResponse")
    @WebResult(name = "GetModelChangePlanResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResultCancelONT getModelChangePlan(

        @WebParam(name = "LngUserId", targetNamespace = "http://tempuri.org/")
        long lngUserId,
        @WebParam(name = "strpwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strpwd,
        @WebParam(name = "strSnHexONT", targetNamespace = "http://tempuri.org/")
        java.lang.String strSnHexONT
    );

    @WebMethod(operationName = "Reconectar_Onts_Red", action = "http://tempuri.org/Reconectar_Onts_Red")
    @RequestWrapper(localName = "Reconectar_Onts_Red", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReconectarOntsRed")
    @ResponseWrapper(localName = "Reconectar_Onts_RedResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReconectarOntsRedResponse")
    public void reconectarOntsRed()
;

    @WebMethod(operationName = "DeleteOntEx", action = "http://tempuri.org/DeleteOntEx")
    @RequestWrapper(localName = "DeleteOntEx", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteOntEx")
    @ResponseWrapper(localName = "DeleteOntExResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteOntExResponse")
    public void deleteOntEx()
;

    @WebMethod(operationName = "CorrecionONT_BigAntenna", action = "http://tempuri.org/CorrecionONT_BigAntenna")
    @RequestWrapper(localName = "CorrecionONT_BigAntenna", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CorrecionONTBigAntenna")
    @ResponseWrapper(localName = "CorrecionONT_BigAntennaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CorrecionONTBigAntennaResponse")
    public void correcionONTBigAntenna()
;

    @WebMethod(operationName = "ExecuteSavedData", action = "http://tempuri.org/ExecuteSavedData")
    @RequestWrapper(localName = "ExecuteSavedData", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteSavedData")
    @ResponseWrapper(localName = "ExecuteSavedDataResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ExecuteSavedDataResponse")
    public void executeSavedData(

        @WebParam(name = "idToRun", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfLong idToRun
    );

    @WebMethod(operationName = "OTNRoutingHSI", action = "http://tempuri.org/OTNRoutingHSI")
    @RequestWrapper(localName = "OTNRoutingHSI", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OTNRoutingHSI")
    @ResponseWrapper(localName = "OTNRoutingHSIResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.OTNRoutingHSIResponse")
    @WebResult(name = "OTNRoutingHSIResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult otnRoutingHSI(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "strSerialNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String strSerialNumber,
        @WebParam(name = "strModeInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strModeInvoke,
        @WebParam(name = "LngUserId", targetNamespace = "http://tempuri.org/")
        long lngUserId,
        @WebParam(name = "strIpInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strIpInvoke,
        @WebParam(name = "intType", targetNamespace = "http://tempuri.org/")
        int intType,
        @WebParam(name = "strMessage", targetNamespace = "http://tempuri.org/")
        java.lang.String strMessage,
        @WebParam(name = "strIdCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String strIdCustomer,
        @WebParam(name = "strFullName", targetNamespace = "http://tempuri.org/")
        java.lang.String strFullName,
        @WebParam(name = "strToPay", targetNamespace = "http://tempuri.org/")
        java.lang.String strToPay,
        @WebParam(name = "strEmail", targetNamespace = "http://tempuri.org/")
        java.lang.String strEmail
    );

    @WebMethod(operationName = "GetONTStatusRoutingHSI", action = "http://tempuri.org/GetONTStatusRoutingHSI")
    @RequestWrapper(localName = "GetONTStatusRoutingHSI", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetONTStatusRoutingHSI")
    @ResponseWrapper(localName = "GetONTStatusRoutingHSIResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetONTStatusRoutingHSIResponse")
    @WebResult(name = "GetONTStatusRoutingHSIResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrsStatusRoutingHSI getONTStatusRoutingHSI(

        @WebParam(name = "strSN", targetNamespace = "http://tempuri.org/")
        java.lang.String strSN,
        @WebParam(name = "intCompany", targetNamespace = "http://tempuri.org/")
        int intCompany
    );

    @WebMethod(operationName = "GetListTmCode", action = "http://tempuri.org/GetListTmCode")
    @RequestWrapper(localName = "GetListTmCode", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetListTmCode")
    @ResponseWrapper(localName = "GetListTmCodeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetListTmCodeResponse")
    @WebResult(name = "GetListTmCodeResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrayOfString getListTmCode();

    @WebMethod(operationName = "ChangeAddressONT", action = "http://tempuri.org/ChangeAddressONT")
    @RequestWrapper(localName = "ChangeAddressONT", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeAddressONT")
    @ResponseWrapper(localName = "ChangeAddressONTResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ChangeAddressONTResponse")
    @WebResult(name = "ChangeAddressONTResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult changeAddressONT(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "arrNewAddressONT", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrParamOptional arrNewAddressONT,
        @WebParam(name = "idPackage", targetNamespace = "http://tempuri.org/")
        long idPackage,
        @WebParam(name = "CustomerId", targetNamespace = "http://tempuri.org/")
        java.lang.String customerId,
        @WebParam(name = "CustomerAlias", targetNamespace = "http://tempuri.org/")
        java.lang.String customerAlias,
        @WebParam(name = "ValuesHSI", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI valuesHSI,
        @WebParam(name = "ValuesVoIP", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP valuesVoIP,
        @WebParam(name = "intCountIPTV", targetNamespace = "http://tempuri.org/")
        int intCountIPTV,
        @WebParam(name = "ArrIPStatic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic arrIPStatic,
        @WebParam(name = "ArrIPDynamic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic arrIPDynamic,
        @WebParam(name = "latitude", targetNamespace = "http://tempuri.org/")
        java.lang.String latitude,
        @WebParam(name = "longitude", targetNamespace = "http://tempuri.org/")
        java.lang.String longitude,
        @WebParam(name = "mail", targetNamespace = "http://tempuri.org/")
        java.lang.String mail,
        @WebParam(name = "zipCode", targetNamespace = "http://tempuri.org/")
        java.lang.String zipCode
    );

    @WebMethod(operationName = "Get_Vendor", action = "http://tempuri.org/Get_Vendor")
    @RequestWrapper(localName = "Get_Vendor", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVendor")
    @ResponseWrapper(localName = "Get_VendorResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetVendorResponse")
    @WebResult(name = "Get_VendorResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.NewVendor getVendor(

        @WebParam(name = "SN", targetNamespace = "http://tempuri.org/")
        java.lang.String sn
    );

    @WebMethod(operationName = "GetDataATA", action = "http://tempuri.org/GetDataATA")
    @RequestWrapper(localName = "GetDataATA", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataATA")
    @ResponseWrapper(localName = "GetDataATAResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDataATAResponse")
    @WebResult(name = "GetDataATAResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelATA getDataATA(

        @WebParam(name = "cuenta", targetNamespace = "http://tempuri.org/")
        java.lang.String cuenta
    );

    @WebMethod(operationName = "QuitRoutingDN", action = "http://tempuri.org/QuitRoutingDN")
    @RequestWrapper(localName = "QuitRoutingDN", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QuitRoutingDN")
    @ResponseWrapper(localName = "QuitRoutingDNResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.QuitRoutingDNResponse")
    @WebResult(name = "QuitRoutingDNResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult quitRoutingDN(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "strOLTName", targetNamespace = "http://tempuri.org/")
        java.lang.String strOLTName,
        @WebParam(name = "CustomerId", targetNamespace = "http://tempuri.org/")
        java.lang.String customerId,
        @WebParam(name = "strName", targetNamespace = "http://tempuri.org/")
        java.lang.String strName,
        @WebParam(name = "strSNONT", targetNamespace = "http://tempuri.org/")
        java.lang.String strSNONT,
        @WebParam(name = "strFrame", targetNamespace = "http://tempuri.org/")
        java.lang.String strFrame,
        @WebParam(name = "strSlot", targetNamespace = "http://tempuri.org/")
        java.lang.String strSlot,
        @WebParam(name = "strPort", targetNamespace = "http://tempuri.org/")
        java.lang.String strPort,
        @WebParam(name = "strONTID", targetNamespace = "http://tempuri.org/")
        java.lang.String strONTID,
        @WebParam(name = "strModeInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strModeInvoke,
        @WebParam(name = "LngUserId", targetNamespace = "http://tempuri.org/")
        long lngUserId,
        @WebParam(name = "strIpInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strIpInvoke,
        @WebParam(name = "blnGuiNew", targetNamespace = "http://tempuri.org/")
        boolean blnGuiNew,
        @WebParam(name = "STRDN", targetNamespace = "http://tempuri.org/")
        java.lang.String strdn
    );

    @WebMethod(operationName = "GetOlts", action = "http://tempuri.org/GetOlts")
    @RequestWrapper(localName = "GetOlts", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOlts")
    @ResponseWrapper(localName = "GetOltsResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetOltsResponse")
    @WebResult(name = "GetOltsResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetCatalogOlts getOlts();

    @WebMethod(operationName = "PackageActivationEnlace", action = "http://tempuri.org/PackageActivationEnlace")
    @RequestWrapper(localName = "PackageActivationEnlace", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageActivationEnlace")
    @ResponseWrapper(localName = "PackageActivationEnlaceResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageActivationEnlaceResponse")
    @WebResult(name = "PackageActivationEnlaceResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult packageActivationEnlace(

        @WebParam(name = "arrActivation", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrActivation arrActivation,
        @WebParam(name = "idPackage", targetNamespace = "http://tempuri.org/")
        long idPackage,
        @WebParam(name = "idCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String idCustomer,
        @WebParam(name = "CustomerName", targetNamespace = "http://tempuri.org/")
        java.lang.String customerName,
        @WebParam(name = "arrAddOnVoIP", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP arrAddOnVoIP,
        @WebParam(name = "ArrAddon", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddons arrAddon,
        @WebParam(name = "blnGaoke", targetNamespace = "http://tempuri.org/")
        boolean blnGaoke,
        @WebParam(name = "blnPreactivation", targetNamespace = "http://tempuri.org/")
        boolean blnPreactivation,
        @WebParam(name = "arrAddOnIptv", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV arrAddOnIptv,
        @WebParam(name = "ArrIPStatic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic arrIPStatic,
        @WebParam(name = "AddInHSFI", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI addInHSFI,
        @WebParam(name = "lngIDaddIP", targetNamespace = "http://tempuri.org/")
        long lngIDaddIP,
        @WebParam(name = "latitude", targetNamespace = "http://tempuri.org/")
        java.lang.String latitude,
        @WebParam(name = "longitude", targetNamespace = "http://tempuri.org/")
        java.lang.String longitude,
        @WebParam(name = "mail", targetNamespace = "http://tempuri.org/")
        java.lang.String mail,
        @WebParam(name = "zipCode", targetNamespace = "http://tempuri.org/")
        java.lang.String zipCode,
        @WebParam(name = "intcounttroncal", targetNamespace = "http://tempuri.org/")
        int intcounttroncal,
        @WebParam(name = "strparamtrunt", targetNamespace = "http://tempuri.org/")
        java.lang.String strparamtrunt,
        @WebParam(name = "strparamIPs", targetNamespace = "http://tempuri.org/")
        java.lang.String strparamIPs,
        @WebParam(name = "strparamIPsDynamic", targetNamespace = "http://tempuri.org/")
        java.lang.String strparamIPsDynamic,
        @WebParam(name = "intCountCCTV", targetNamespace = "http://tempuri.org/")
        int intCountCCTV
    );

    @WebMethod(operationName = "EliminaUserAAA", action = "http://tempuri.org/EliminaUserAAA")
    @RequestWrapper(localName = "EliminaUserAAA", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminaUserAAA")
    @ResponseWrapper(localName = "EliminaUserAAAResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.EliminaUserAAAResponse")
    public void eliminaUserAAA()
;

    @WebMethod(operationName = "insert_ATA", action = "http://tempuri.org/insert_ATA")
    @RequestWrapper(localName = "insert_ATA", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertATA")
    @ResponseWrapper(localName = "insert_ATAResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.InsertATAResponse")
    @WebResult(name = "insert_ATAResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult insertATA(

        @WebParam(name = "ATA_cuenta", targetNamespace = "http://tempuri.org/")
        java.lang.String ataCuenta,
        @WebParam(name = "ATA_SN", targetNamespace = "http://tempuri.org/")
        java.lang.String ataSN,
        @WebParam(name = "ATA_POT", targetNamespace = "http://tempuri.org/")
        java.lang.String ataPOT,
        @WebParam(name = "ATA_DN", targetNamespace = "http://tempuri.org/")
        java.lang.String ataDN,
        @WebParam(name = "ATA_STATUS", targetNamespace = "http://tempuri.org/")
        java.lang.String ataSTATUS,
        @WebParam(name = "ATA_DOMINIO", targetNamespace = "http://tempuri.org/")
        java.lang.String ataDOMINIO
    );

    /**
     * Obtiene Informacion de cuentas
     */
    @WebMethod(operationName = "CreateUserAAAReporte", action = "http://tempuri.org/CreateUserAAAReporte")
    @RequestWrapper(localName = "CreateUserAAAReporte", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateUserAAAReporte")
    @ResponseWrapper(localName = "CreateUserAAAReporteResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateUserAAAReporteResponse")
    public void createUserAAAReporte()
;

    @WebMethod(operationName = "Decript", action = "http://tempuri.org/Decript")
    @RequestWrapper(localName = "Decript", targetNamespace = "http://tempuri.org/", className = "org.tempuri.Decript")
    @ResponseWrapper(localName = "DecriptResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DecriptResponse")
    @WebResult(name = "DecriptResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String decript(

        @WebParam(name = "IDModel", targetNamespace = "http://tempuri.org/")
        java.lang.String idModel
    );

    @WebMethod(operationName = "validate_bd", action = "http://tempuri.org/validate_bd")
    @RequestWrapper(localName = "validate_bd", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateBd")
    @ResponseWrapper(localName = "validate_bdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidateBdResponse")
    @WebResult(name = "validate_bdResult", targetNamespace = "http://tempuri.org/")
    public java.lang.String validateBd(

        @WebParam(name = "usr", targetNamespace = "http://tempuri.org/")
        java.lang.String usr,
        @WebParam(name = "test", targetNamespace = "http://tempuri.org/")
        java.lang.String test
    );

    @WebMethod(operationName = "ObtIDActivacion", action = "http://tempuri.org/ObtIDActivacion")
    @RequestWrapper(localName = "ObtIDActivacion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtIDActivacion")
    @ResponseWrapper(localName = "ObtIDActivacionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ObtIDActivacionResponse")
    @WebResult(name = "ObtIDActivacionResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.IDTransactionActivation obtIDActivacion(

        @WebParam(name = "idcustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String idcustomer
    );

    @WebMethod(operationName = "DeleteONTSync", action = "http://tempuri.org/DeleteONTSync")
    @RequestWrapper(localName = "DeleteONTSync", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteONTSync")
    @ResponseWrapper(localName = "DeleteONTSyncResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteONTSyncResponse")
    @WebResult(name = "DeleteONTSyncResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResultCancelONT deleteONTSync(

        @WebParam(name = "LngUserId", targetNamespace = "http://tempuri.org/")
        long lngUserId,
        @WebParam(name = "strpwd", targetNamespace = "http://tempuri.org/")
        java.lang.String strpwd,
        @WebParam(name = "strSNONT", targetNamespace = "http://tempuri.org/")
        java.lang.String strSNONT
    );

    @WebMethod(operationName = "Delete_ATA", action = "http://tempuri.org/Delete_ATA")
    @RequestWrapper(localName = "Delete_ATA", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteATA")
    @ResponseWrapper(localName = "Delete_ATAResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteATAResponse")
    @WebResult(name = "Delete_ATAResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult deleteATA(

        @WebParam(name = "cuenta", targetNamespace = "http://tempuri.org/")
        java.lang.String cuenta,
        @WebParam(name = "DN", targetNamespace = "http://tempuri.org/")
        java.lang.String dn
    );

    @WebMethod(operationName = "CreateDN", action = "http://tempuri.org/CreateDN")
    @RequestWrapper(localName = "CreateDN", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateDN")
    @ResponseWrapper(localName = "CreateDNResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CreateDNResponse")
    @WebResult(name = "CreateDNResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult createDN(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "strOLTName", targetNamespace = "http://tempuri.org/")
        java.lang.String strOLTName,
        @WebParam(name = "CustomerId", targetNamespace = "http://tempuri.org/")
        java.lang.String customerId,
        @WebParam(name = "strName", targetNamespace = "http://tempuri.org/")
        java.lang.String strName,
        @WebParam(name = "strSNONT", targetNamespace = "http://tempuri.org/")
        java.lang.String strSNONT,
        @WebParam(name = "strFrame", targetNamespace = "http://tempuri.org/")
        java.lang.String strFrame,
        @WebParam(name = "strSlot", targetNamespace = "http://tempuri.org/")
        java.lang.String strSlot,
        @WebParam(name = "strPort", targetNamespace = "http://tempuri.org/")
        java.lang.String strPort,
        @WebParam(name = "strONTID", targetNamespace = "http://tempuri.org/")
        java.lang.String strONTID,
        @WebParam(name = "strModeInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strModeInvoke,
        @WebParam(name = "LngUserId", targetNamespace = "http://tempuri.org/")
        long lngUserId,
        @WebParam(name = "strIpInvoke", targetNamespace = "http://tempuri.org/")
        java.lang.String strIpInvoke,
        @WebParam(name = "blnGuiNew", targetNamespace = "http://tempuri.org/")
        boolean blnGuiNew,
        @WebParam(name = "STRDN", targetNamespace = "http://tempuri.org/")
        java.lang.String strdn
    );

    @WebMethod(operationName = "PackageActivation", action = "http://tempuri.org/PackageActivation")
    @RequestWrapper(localName = "PackageActivation", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageActivation")
    @ResponseWrapper(localName = "PackageActivationResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageActivationResponse")
    @WebResult(name = "PackageActivationResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult packageActivation(

        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "arrActivation", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrActivation arrActivation,
        @WebParam(name = "idPackage", targetNamespace = "http://tempuri.org/")
        long idPackage,
        @WebParam(name = "idCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String idCustomer,
        @WebParam(name = "CustomerAlias", targetNamespace = "http://tempuri.org/")
        java.lang.String customerAlias,
        @WebParam(name = "AddInHSFI", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI addInHSFI,
        @WebParam(name = "arrAddInVoIP", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP arrAddInVoIP,
        @WebParam(name = "AddInIPTV", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV addInIPTV,
        @WebParam(name = "ArrAddon", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddons arrAddon,
        @WebParam(name = "ArrIPStatic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic arrIPStatic,
        @WebParam(name = "ArrIPDynamic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic arrIPDynamic,
        @WebParam(name = "latitude", targetNamespace = "http://tempuri.org/")
        java.lang.String latitude,
        @WebParam(name = "longitude", targetNamespace = "http://tempuri.org/")
        java.lang.String longitude,
        @WebParam(name = "mail", targetNamespace = "http://tempuri.org/")
        java.lang.String mail,
        @WebParam(name = "zipCode", targetNamespace = "http://tempuri.org/")
        java.lang.String zipCode
    );

    @WebMethod(operationName = "Activacion_Consulta_Datos", action = "http://tempuri.org/Activacion_Consulta_Datos")
    @RequestWrapper(localName = "Activacion_Consulta_Datos", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActivacionConsultaDatos")
    @ResponseWrapper(localName = "Activacion_Consulta_DatosResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ActivacionConsultaDatosResponse")
    @WebResult(name = "Activacion_Consulta_DatosResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetONT activacionConsultaDatos(

        @WebParam(name = "strvalue", targetNamespace = "http://tempuri.org/")
        java.lang.String strvalue
    );

    @WebMethod(operationName = "PackageActivationFusion", action = "http://tempuri.org/PackageActivationFusion")
    @RequestWrapper(localName = "PackageActivationFusion", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageActivationFusion")
    @ResponseWrapper(localName = "PackageActivationFusionResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PackageActivationFusionResponse")
    @WebResult(name = "PackageActivationFusionResult", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResult packageActivationFusion(

        @WebParam(name = "ArrBrm", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrBrm arrBrm,
        @WebParam(name = "Login", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrLogin login,
        @WebParam(name = "arrActivation", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrActivation arrActivation,
        @WebParam(name = "idPackage", targetNamespace = "http://tempuri.org/")
        long idPackage,
        @WebParam(name = "idCustomer", targetNamespace = "http://tempuri.org/")
        java.lang.String idCustomer,
        @WebParam(name = "CustomerAlias", targetNamespace = "http://tempuri.org/")
        java.lang.String customerAlias,
        @WebParam(name = "AddInHSFI", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI addInHSFI,
        @WebParam(name = "arrAddInVoIP", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP arrAddInVoIP,
        @WebParam(name = "AddInIPTV", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV addInIPTV,
        @WebParam(name = "ArrAddon", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrAddons arrAddon,
        @WebParam(name = "ArrIPStatic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic arrIPStatic,
        @WebParam(name = "ArrIPDynamic", targetNamespace = "http://tempuri.org/")
        com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic arrIPDynamic,
        @WebParam(name = "latitude", targetNamespace = "http://tempuri.org/")
        java.lang.String latitude,
        @WebParam(name = "longitude", targetNamespace = "http://tempuri.org/")
        java.lang.String longitude,
        @WebParam(name = "mail", targetNamespace = "http://tempuri.org/")
        java.lang.String mail,
        @WebParam(name = "zipCode", targetNamespace = "http://tempuri.org/")
        java.lang.String zipCode
    );

    @WebMethod(operationName = "GetIPWAN_TR069", action = "http://tempuri.org/GetIPWAN_TR069")
    @RequestWrapper(localName = "GetIPWAN_TR069", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIPWANTR069")
    @ResponseWrapper(localName = "GetIPWAN_TR069Response", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetIPWANTR069Response")
    @WebResult(name = "GetIPWAN_TR069Result", targetNamespace = "http://tempuri.org/")
    public com.totaplay.searchONT.tprovisioningSoa.ArrResIPWAN getIPWANTR069(

        @WebParam(name = "strSN", targetNamespace = "http://tempuri.org/")
        java.lang.String strSN
    );
}
