
package com.totaplay.searchONT.tprovisioningSoa;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.0
 * 2022-02-14T19:56:28.503-06:00
 * Generated source version: 3.5.0
 *
 */
public final class TProvisioningSoap_TProvisioningSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://tempuri.org/", "TProvisioning");

    private TProvisioningSoap_TProvisioningSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TProvisioning.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TProvisioning ss = new TProvisioning(wsdlURL, SERVICE_NAME);
        TProvisioningSoap port = ss.getTProvisioningSoap();

        {
        System.out.println("Invoking getModels...");
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetcatalog _getModels__return = port.getModels();
        System.out.println("getModels.result=" + _getModels__return);


        }
        {
        System.out.println("Invoking quitRoutingIPTV...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _quitRoutingIPTV_login = null;
        java.lang.String _quitRoutingIPTV_strOLTName = "";
        java.lang.String _quitRoutingIPTV_customerId = "";
        java.lang.String _quitRoutingIPTV_strName = "";
        java.lang.String _quitRoutingIPTV_strSNONT = "";
        java.lang.String _quitRoutingIPTV_strFrame = "";
        java.lang.String _quitRoutingIPTV_strSlot = "";
        java.lang.String _quitRoutingIPTV_strPort = "";
        java.lang.String _quitRoutingIPTV_strONTID = "";
        java.lang.String _quitRoutingIPTV_strModeInvoke = "";
        long _quitRoutingIPTV_lngUserId = 0;
        java.lang.String _quitRoutingIPTV_strIpInvoke = "";
        boolean _quitRoutingIPTV_blnGuiNew = false;
        java.lang.String _quitRoutingIPTV_strdn = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _quitRoutingIPTV__return = port.quitRoutingIPTV(_quitRoutingIPTV_login, _quitRoutingIPTV_strOLTName, _quitRoutingIPTV_customerId, _quitRoutingIPTV_strName, _quitRoutingIPTV_strSNONT, _quitRoutingIPTV_strFrame, _quitRoutingIPTV_strSlot, _quitRoutingIPTV_strPort, _quitRoutingIPTV_strONTID, _quitRoutingIPTV_strModeInvoke, _quitRoutingIPTV_lngUserId, _quitRoutingIPTV_strIpInvoke, _quitRoutingIPTV_blnGuiNew, _quitRoutingIPTV_strdn);
        System.out.println("quitRoutingIPTV.result=" + _quitRoutingIPTV__return);


        }
        {
        System.out.println("Invoking getRegionByOLT...");
        java.lang.String _getRegionByOLT_olt = "";
        int _getRegionByOLT__return = port.getRegionByOLT(_getRegionByOLT_olt);
        System.out.println("getRegionByOLT.result=" + _getRegionByOLT__return);


        }
        {
        System.out.println("Invoking getAutoFindTL1BySNsf...");
        java.lang.String _getAutoFindTL1BySNsf_strSerialNumber = "";
        java.lang.String _getAutoFindTL1BySNsf_strUser = "";
        java.lang.String _getAutoFindTL1BySNsf_strPWD = "";
            com.totaplay.searchONT.tprovisioningSoa.AutofindONT _getAutoFindTL1BySNsf__return = port.getAutoFindTL1BySNsf(_getAutoFindTL1BySNsf_strSerialNumber, _getAutoFindTL1BySNsf_strUser, _getAutoFindTL1BySNsf_strPWD);
        System.out.println("getAutoFindTL1BySNsf.result=" + _getAutoFindTL1BySNsf__return);


        }
        {
        System.out.println("Invoking suppression...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _suppression_login = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrActivation _suppression_arrActivation = null;
        long _suppression_idPackage = 0;
        java.lang.String _suppression_idCustomer = "";
        java.lang.String _suppression_customerAlias = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP _suppression_inVoIPs = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV _suppression_inIPTVs = null;
        java.lang.String _suppression_strDnMaster = "";
        java.lang.String _suppression_periodHrs = "";
        javax.xml.datatype.XMLGregorianCalendar _suppression_dteLimit = null;
        int _suppression_intReason = 0;
        java.lang.String _suppression_strComments = "";
        java.lang.String _suppression_strIdUserEvergent = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _suppression__return = port.suppression(_suppression_login, _suppression_arrActivation, _suppression_idPackage, _suppression_idCustomer, _suppression_customerAlias, _suppression_inVoIPs, _suppression_inIPTVs, _suppression_strDnMaster, _suppression_periodHrs, _suppression_dteLimit, _suppression_intReason, _suppression_strComments, _suppression_strIdUserEvergent);
        System.out.println("suppression.result=" + _suppression__return);


        }
        {
        System.out.println("Invoking getSearchONTDash...");
        java.lang.String _getSearchONTDash_strvalue = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetONT _getSearchONTDash__return = port.getSearchONTDash(_getSearchONTDash_strvalue);
        System.out.println("getSearchONTDash.result=" + _getSearchONTDash__return);


        }
        {
        System.out.println("Invoking getOLTVendor...");
        java.lang.String _getOLTVendor_oltName = "";
        int _getOLTVendor__return = port.getOLTVendor(_getOLTVendor_oltName);
        System.out.println("getOLTVendor.result=" + _getOLTVendor__return);


        }
        {
        System.out.println("Invoking cancelONTU200...");
            com.totaplay.searchONT.tprovisioningSoa.FilterOLTS _cancelONTU200_filter = null;
        java.lang.String _cancelONTU200_strModeInvoke = "";
        long _cancelONTU200_lngUserId = 0;
        java.lang.String _cancelONTU200_strIpInvoke = "";
        boolean _cancelONTU200_blnGuiNew = false;
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _cancelONTU200__return = port.cancelONTU200(_cancelONTU200_filter, _cancelONTU200_strModeInvoke, _cancelONTU200_lngUserId, _cancelONTU200_strIpInvoke, _cancelONTU200_blnGuiNew);
        System.out.println("cancelONTU200.result=" + _cancelONTU200__return);


        }
        {
        System.out.println("Invoking packageActivationEnlaceFusion...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _packageActivationEnlaceFusion_login = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrActivation _packageActivationEnlaceFusion_arrActivation = null;
        long _packageActivationEnlaceFusion_idPackage = 0;
        java.lang.String _packageActivationEnlaceFusion_idCustomer = "";
        java.lang.String _packageActivationEnlaceFusion_customerAlias = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI _packageActivationEnlaceFusion_addInHSFI = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP _packageActivationEnlaceFusion_arrAddInVoIP = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP _packageActivationEnlaceFusion_arrAddInVoIPTroncal = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic _packageActivationEnlaceFusion_arrIPStatic = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic _packageActivationEnlaceFusion_arrIPDynamic = null;
        long _packageActivationEnlaceFusion_lngIDaddIP = 0;
        int _packageActivationEnlaceFusion_intcounttroncal = 0;
        java.lang.String _packageActivationEnlaceFusion_strparamIPsStatic = "";
        java.lang.String _packageActivationEnlaceFusion_strCCTV = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrIPStaticCCTV _packageActivationEnlaceFusion_arrIPStaticCCTV = null;
        int _packageActivationEnlaceFusion_intEncoderTV = 0;
        int _packageActivationEnlaceFusion_intCountCCTV = 0;
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _packageActivationEnlaceFusion__return = port.packageActivationEnlaceFusion(_packageActivationEnlaceFusion_login, _packageActivationEnlaceFusion_arrActivation, _packageActivationEnlaceFusion_idPackage, _packageActivationEnlaceFusion_idCustomer, _packageActivationEnlaceFusion_customerAlias, _packageActivationEnlaceFusion_addInHSFI, _packageActivationEnlaceFusion_arrAddInVoIP, _packageActivationEnlaceFusion_arrAddInVoIPTroncal, _packageActivationEnlaceFusion_arrIPStatic, _packageActivationEnlaceFusion_arrIPDynamic, _packageActivationEnlaceFusion_lngIDaddIP, _packageActivationEnlaceFusion_intcounttroncal, _packageActivationEnlaceFusion_strparamIPsStatic, _packageActivationEnlaceFusion_strCCTV, _packageActivationEnlaceFusion_arrIPStaticCCTV, _packageActivationEnlaceFusion_intEncoderTV, _packageActivationEnlaceFusion_intCountCCTV);
        System.out.println("packageActivationEnlaceFusion.result=" + _packageActivationEnlaceFusion__return);


        }
        {
        System.out.println("Invoking deleteActivation...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _deleteActivation_login = null;
        java.lang.String _deleteActivation_idCustomer = "";
            com.totaplay.searchONT.tprovisioningSoa.ModelGetONT _deleteActivation_arrActivation = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP _deleteActivation_arrVoIP = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV _deleteActivation_arrIPTV = null;
        java.lang.String _deleteActivation_strDnMaster = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _deleteActivation__return = port.deleteActivation(_deleteActivation_login, _deleteActivation_idCustomer, _deleteActivation_arrActivation, _deleteActivation_arrVoIP, _deleteActivation_arrIPTV, _deleteActivation_strDnMaster);
        System.out.println("deleteActivation.result=" + _deleteActivation__return);


        }
        {
        System.out.println("Invoking upgrade...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _upgrade_login = null;
            com.totaplay.searchONT.tprovisioningSoa.DtoDeleteActivation _upgrade_deleteActivation = null;
            com.totaplay.searchONT.tprovisioningSoa.DtoPackageActivation _upgrade_packageActivation = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _upgrade__return = port.upgrade(_upgrade_login, _upgrade_deleteActivation, _upgrade_packageActivation);
        System.out.println("upgrade.result=" + _upgrade__return);


        }
        {
        System.out.println("Invoking testONT...");
        java.lang.String _testONT_strOLT = "";
        java.lang.String _testONT_strFrame = "";
        java.lang.String _testONT_strSlot = "";
        java.lang.String _testONT_strPort = "";
        java.lang.String _testONT_strONTID = "";
        java.lang.String _testONT_strserialnumber = "";
        java.lang.String _testONT_idCustomer = "";
        long _testONT_lngUserId = 0;
        java.lang.String _testONT_strIpInvoke = "";
        java.lang.String _testONT_strModeInvoke = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _testONT__return = port.testONT(_testONT_strOLT, _testONT_strFrame, _testONT_strSlot, _testONT_strPort, _testONT_strONTID, _testONT_strserialnumber, _testONT_idCustomer, _testONT_lngUserId, _testONT_strIpInvoke, _testONT_strModeInvoke);
        System.out.println("testONT.result=" + _testONT__return);


        }
        {
        System.out.println("Invoking procesaActHorario...");
        java.lang.String _procesaActHorario_cuenta = "";
        port.procesaActHorario(_procesaActHorario_cuenta);


        }
        {
        System.out.println("Invoking getAlarms...");
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfString _getAlarms_lstrSN = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfGetALarm _getAlarms__return = port.getAlarms(_getAlarms_lstrSN);
        System.out.println("getAlarms.result=" + _getAlarms__return);


        }
        {
        System.out.println("Invoking reAprovOntsRed...");
        port.reAprovOntsRed();


        }
        {
        System.out.println("Invoking createUserAAAMasivo...");
        port.createUserAAAMasivo();


        }
        {
        System.out.println("Invoking getNetworkInformation...");
        java.lang.String _getNetworkInformation_strSerialNumber = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrNetwork _getNetworkInformation__return = port.getNetworkInformation(_getNetworkInformation_strSerialNumber);
        System.out.println("getNetworkInformation.result=" + _getNetworkInformation__return);


        }
        {
        System.out.println("Invoking deleteDN...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _deleteDN_login = null;
        java.lang.String _deleteDN_strOLTName = "";
        java.lang.String _deleteDN_customerId = "";
        java.lang.String _deleteDN_strName = "";
        java.lang.String _deleteDN_strSNONT = "";
        java.lang.String _deleteDN_strFrame = "";
        java.lang.String _deleteDN_strSlot = "";
        java.lang.String _deleteDN_strPort = "";
        java.lang.String _deleteDN_strONTID = "";
        java.lang.String _deleteDN_strModeInvoke = "";
        long _deleteDN_lngUserId = 0;
        java.lang.String _deleteDN_strIpInvoke = "";
        boolean _deleteDN_blnGuiNew = false;
        java.lang.String _deleteDN_strdn = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _deleteDN__return = port.deleteDN(_deleteDN_login, _deleteDN_strOLTName, _deleteDN_customerId, _deleteDN_strName, _deleteDN_strSNONT, _deleteDN_strFrame, _deleteDN_strSlot, _deleteDN_strPort, _deleteDN_strONTID, _deleteDN_strModeInvoke, _deleteDN_lngUserId, _deleteDN_strIpInvoke, _deleteDN_blnGuiNew, _deleteDN_strdn);
        System.out.println("deleteDN.result=" + _deleteDN__return);


        }
        {
        System.out.println("Invoking reAprovOntsRedSN...");
        port.reAprovOntsRedSN();


        }
        {
        System.out.println("Invoking getSearchONT...");
        java.lang.String _getSearchONT_strvalue = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetONT _getSearchONT__return = port.getSearchONT(_getSearchONT_strvalue);
        System.out.println("getSearchONT.result=" + _getSearchONT__return);


        }
        {
        System.out.println("Invoking getAutoFind...");
        java.lang.String _getAutoFind_strSerialNumber = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrAutoFind _getAutoFind__return = port.getAutoFind(_getAutoFind_strSerialNumber);
        System.out.println("getAutoFind.result=" + _getAutoFind__return);


        }
        {
        System.out.println("Invoking getIPTR069...");
        java.lang.String _getIPTR069_strSN = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrWANIP _getIPTR069__return = port.getIPTR069(_getIPTR069_strSN);
        System.out.println("getIPTR069.result=" + _getIPTR069__return);


        }
        {
        System.out.println("Invoking validAddDrmCustomerProfileFusion...");
            com.totaplay.searchONT.tprovisioningSoa.ArrBrm _validAddDrmCustomerProfileFusion_arrBrm = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrActivation _validAddDrmCustomerProfileFusion_arrActivation = null;
        long _validAddDrmCustomerProfileFusion_lngIdPackage = 0;
        java.lang.String _validAddDrmCustomerProfileFusion_strIdCustomer = "";
        java.lang.String _validAddDrmCustomerProfileFusion_strCustomerAlias = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP _validAddDrmCustomerProfileFusion_arrAddOnVoIP = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrAddons _validAddDrmCustomerProfileFusion_arrAddon = null;
        int _validAddDrmCustomerProfileFusion_intCountVoip = 0;
        int _validAddDrmCustomerProfileFusion_strDown = 0;
        int _validAddDrmCustomerProfileFusion_strUp = 0;
        int _validAddDrmCustomerProfileFusion_intCountHSI = 0;
        java.lang.String _validAddDrmCustomerProfileFusion_strTypeInvoke = "";
        int _validAddDrmCustomerProfileFusion_intCountTV = 0;
        java.lang.String _validAddDrmCustomerProfileFusion_idCustomer = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV _validAddDrmCustomerProfileFusion_arrAddOnIptv = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI _validAddDrmCustomerProfileFusion_addInHSFI = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic _validAddDrmCustomerProfileFusion_arrIPStatic = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic _validAddDrmCustomerProfileFusion_arrIPDynamic = null;
            com.totaplay.searchONT.tprovisioningSoa.MdlBscQry _validAddDrmCustomerProfileFusion_mdlBscsQry = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrRoutingHSI _validAddDrmCustomerProfileFusion_ontcon = null;
        boolean _validAddDrmCustomerProfileFusion_blnExistONT = false;
            com.totaplay.searchONT.tprovisioningSoa.MdlGeneralsSystem _validAddDrmCustomerProfileFusion_mdlgenerals = null;
        boolean _validAddDrmCustomerProfileFusion_blnConect = false;
            com.totaplay.searchONT.tprovisioningSoa.ArrAutoFind _validAddDrmCustomerProfileFusion_srrfing = null;
        java.lang.String _validAddDrmCustomerProfileFusion_strVersion = "";
            com.totaplay.searchONT.tprovisioningSoa.ModelGetModelPorts _validAddDrmCustomerProfileFusion_mdlPOrts = null;
        boolean _validAddDrmCustomerProfileFusion_blnGaoke = false;
        java.lang.String _validAddDrmCustomerProfileFusion_strModel = "";
            com.totaplay.searchONT.tprovisioningSoa.ModelValidReturn _validAddDrmCustomerProfileFusion__return = port.validAddDrmCustomerProfileFusion(_validAddDrmCustomerProfileFusion_arrBrm, _validAddDrmCustomerProfileFusion_arrActivation, _validAddDrmCustomerProfileFusion_lngIdPackage, _validAddDrmCustomerProfileFusion_strIdCustomer, _validAddDrmCustomerProfileFusion_strCustomerAlias, _validAddDrmCustomerProfileFusion_arrAddOnVoIP, _validAddDrmCustomerProfileFusion_arrAddon, _validAddDrmCustomerProfileFusion_intCountVoip, _validAddDrmCustomerProfileFusion_strDown, _validAddDrmCustomerProfileFusion_strUp, _validAddDrmCustomerProfileFusion_intCountHSI, _validAddDrmCustomerProfileFusion_strTypeInvoke, _validAddDrmCustomerProfileFusion_intCountTV, _validAddDrmCustomerProfileFusion_idCustomer, _validAddDrmCustomerProfileFusion_arrAddOnIptv, _validAddDrmCustomerProfileFusion_addInHSFI, _validAddDrmCustomerProfileFusion_arrIPStatic, _validAddDrmCustomerProfileFusion_arrIPDynamic, _validAddDrmCustomerProfileFusion_mdlBscsQry, _validAddDrmCustomerProfileFusion_ontcon, _validAddDrmCustomerProfileFusion_blnExistONT, _validAddDrmCustomerProfileFusion_mdlgenerals, _validAddDrmCustomerProfileFusion_blnConect, _validAddDrmCustomerProfileFusion_srrfing, _validAddDrmCustomerProfileFusion_strVersion, _validAddDrmCustomerProfileFusion_mdlPOrts, _validAddDrmCustomerProfileFusion_blnGaoke, _validAddDrmCustomerProfileFusion_strModel);
        System.out.println("validAddDrmCustomerProfileFusion.result=" + _validAddDrmCustomerProfileFusion__return);


        }
        {
        System.out.println("Invoking reconectaDns...");
        port.reconectaDns();


        }
        {
        System.out.println("Invoking setAdon...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _setAdon_login = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrActivation _setAdon_arrONT = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrAddons _setAdon_arrAddon = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic _setAdon_arrIPStatic = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _setAdon__return = port.setAdon(_setAdon_login, _setAdon_arrONT, _setAdon_arrAddon, _setAdon_arrIPStatic);
        System.out.println("setAdon.result=" + _setAdon__return);


        }
        {
        System.out.println("Invoking getOpticalONT...");
        java.lang.String _getOpticalONT_strOLTName = "";
        java.lang.String _getOpticalONT_strFrame = "";
        java.lang.String _getOpticalONT_strSlot = "";
        java.lang.String _getOpticalONT_strPort = "";
        java.lang.String _getOpticalONT_strONTID = "";
        java.lang.String _getOpticalONT_user = "";
            com.totaplay.searchONT.tprovisioningSoa.OntOptical _getOpticalONT__return = port.getOpticalONT(_getOpticalONT_strOLTName, _getOpticalONT_strFrame, _getOpticalONT_strSlot, _getOpticalONT_strPort, _getOpticalONT_strONTID, _getOpticalONT_user);
        System.out.println("getOpticalONT.result=" + _getOpticalONT__return);


        }
        {
        System.out.println("Invoking reAprovOntsRed3...");
        port.reAprovOntsRed3();


        }
        {
        System.out.println("Invoking changeONT...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _changeONT_login = null;
        java.lang.String _changeONT_customerId = "";
        java.lang.String _changeONT_newSerialONT = "";
        long _changeONT_idModel = 0;
        java.lang.String _changeONT_strOldSerialNumber = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _changeONT__return = port.changeONT(_changeONT_login, _changeONT_customerId, _changeONT_newSerialONT, _changeONT_idModel, _changeONT_strOldSerialNumber);
        System.out.println("changeONT.result=" + _changeONT__return);


        }
        {
        System.out.println("Invoking reAprovOntsRed2...");
        port.reAprovOntsRed2();


        }
        {
        System.out.println("Invoking updateATA...");
        java.lang.String _updateATA_cuenta = "";
        java.lang.String _updateATA_dn = "";
        java.lang.String _updateATA_pot = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _updateATA__return = port.updateATA(_updateATA_cuenta, _updateATA_dn, _updateATA_pot);
        System.out.println("updateATA.result=" + _updateATA__return);


        }
        {
        System.out.println("Invoking getListTmCodeTWO...");
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfString _getListTmCodeTWO__return = port.getListTmCodeTWO();
        System.out.println("getListTmCodeTWO.result=" + _getListTmCodeTWO__return);


        }
        {
        System.out.println("Invoking reAprovOntsRed4...");
        port.reAprovOntsRed4();


        }
        {
        System.out.println("Invoking validAddDrmCustomerProfileFusionEnlace...");
            com.totaplay.searchONT.tprovisioningSoa.ArrActivation _validAddDrmCustomerProfileFusionEnlace_arrActivation = null;
        long _validAddDrmCustomerProfileFusionEnlace_lngIdPackage = 0;
        java.lang.String _validAddDrmCustomerProfileFusionEnlace_strIdCustomer = "";
        java.lang.String _validAddDrmCustomerProfileFusionEnlace_strCustomerAlias = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP _validAddDrmCustomerProfileFusionEnlace_arrAddOnVoIP = null;
        java.lang.String _validAddDrmCustomerProfileFusionEnlace_strTypeInvoke = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI _validAddDrmCustomerProfileFusionEnlace_addInHSFI = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic _validAddDrmCustomerProfileFusionEnlace_arrIPStatic = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic _validAddDrmCustomerProfileFusionEnlace_arrIPDynamic = null;
        int _validAddDrmCustomerProfileFusionEnlace_intcounttroncal = 0;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPStaticCCTV _validAddDrmCustomerProfileFusionEnlace_arrIPStaticCCTV = null;
            com.totaplay.searchONT.tprovisioningSoa.ModelValidReturn _validAddDrmCustomerProfileFusionEnlace__return = port.validAddDrmCustomerProfileFusionEnlace(_validAddDrmCustomerProfileFusionEnlace_arrActivation, _validAddDrmCustomerProfileFusionEnlace_lngIdPackage, _validAddDrmCustomerProfileFusionEnlace_strIdCustomer, _validAddDrmCustomerProfileFusionEnlace_strCustomerAlias, _validAddDrmCustomerProfileFusionEnlace_arrAddOnVoIP, _validAddDrmCustomerProfileFusionEnlace_strTypeInvoke, _validAddDrmCustomerProfileFusionEnlace_addInHSFI, _validAddDrmCustomerProfileFusionEnlace_arrIPStatic, _validAddDrmCustomerProfileFusionEnlace_arrIPDynamic, _validAddDrmCustomerProfileFusionEnlace_intcounttroncal, _validAddDrmCustomerProfileFusionEnlace_arrIPStaticCCTV);
        System.out.println("validAddDrmCustomerProfileFusionEnlace.result=" + _validAddDrmCustomerProfileFusionEnlace__return);


        }
        {
        System.out.println("Invoking changeVoip...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _changeVoip_login = null;
        java.lang.String _changeVoip_customerId = "";
        java.lang.String _changeVoip_strSerialNumber = "";
        java.lang.String _changeVoip_strNewDN = "";
        java.lang.String _changeVoip_strOldDN = "";
        boolean _changeVoip_blnMaster = false;
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _changeVoip__return = port.changeVoip(_changeVoip_login, _changeVoip_customerId, _changeVoip_strSerialNumber, _changeVoip_strNewDN, _changeVoip_strOldDN, _changeVoip_blnMaster);
        System.out.println("changeVoip.result=" + _changeVoip__return);


        }
        {
        System.out.println("Invoking getModelChangePlan...");
        long _getModelChangePlan_lngUserId = 0;
        java.lang.String _getModelChangePlan_strpwd = "";
        java.lang.String _getModelChangePlan_strSnHexONT = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResultCancelONT _getModelChangePlan__return = port.getModelChangePlan(_getModelChangePlan_lngUserId, _getModelChangePlan_strpwd, _getModelChangePlan_strSnHexONT);
        System.out.println("getModelChangePlan.result=" + _getModelChangePlan__return);


        }
        {
        System.out.println("Invoking reconectarOntsRed...");
        port.reconectarOntsRed();


        }
        {
        System.out.println("Invoking deleteOntEx...");
        port.deleteOntEx();


        }
        {
        System.out.println("Invoking correcionONTBigAntenna...");
        port.correcionONTBigAntenna();


        }
        {
        System.out.println("Invoking executeSavedData...");
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfLong _executeSavedData_idToRun = null;
        port.executeSavedData(_executeSavedData_idToRun);


        }
        {
        System.out.println("Invoking otnRoutingHSI...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _otnRoutingHSI_login = null;
        java.lang.String _otnRoutingHSI_strSerialNumber = "";
        java.lang.String _otnRoutingHSI_strModeInvoke = "";
        long _otnRoutingHSI_lngUserId = 0;
        java.lang.String _otnRoutingHSI_strIpInvoke = "";
        int _otnRoutingHSI_intType = 0;
        java.lang.String _otnRoutingHSI_strMessage = "";
        java.lang.String _otnRoutingHSI_strIdCustomer = "";
        java.lang.String _otnRoutingHSI_strFullName = "";
        java.lang.String _otnRoutingHSI_strToPay = "";
        java.lang.String _otnRoutingHSI_strEmail = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _otnRoutingHSI__return = port.otnRoutingHSI(_otnRoutingHSI_login, _otnRoutingHSI_strSerialNumber, _otnRoutingHSI_strModeInvoke, _otnRoutingHSI_lngUserId, _otnRoutingHSI_strIpInvoke, _otnRoutingHSI_intType, _otnRoutingHSI_strMessage, _otnRoutingHSI_strIdCustomer, _otnRoutingHSI_strFullName, _otnRoutingHSI_strToPay, _otnRoutingHSI_strEmail);
        System.out.println("otnRoutingHSI.result=" + _otnRoutingHSI__return);


        }
        {
        System.out.println("Invoking getONTStatusRoutingHSI...");
        java.lang.String _getONTStatusRoutingHSI_strSN = "";
        int _getONTStatusRoutingHSI_intCompany = 0;
            com.totaplay.searchONT.tprovisioningSoa.ArrsStatusRoutingHSI _getONTStatusRoutingHSI__return = port.getONTStatusRoutingHSI(_getONTStatusRoutingHSI_strSN, _getONTStatusRoutingHSI_intCompany);
        System.out.println("getONTStatusRoutingHSI.result=" + _getONTStatusRoutingHSI__return);


        }
        {
        System.out.println("Invoking getListTmCode...");
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfString _getListTmCode__return = port.getListTmCode();
        System.out.println("getListTmCode.result=" + _getListTmCode__return);


        }
        {
        System.out.println("Invoking changeAddressONT...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _changeAddressONT_login = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrParamOptional _changeAddressONT_arrNewAddressONT = null;
        long _changeAddressONT_idPackage = 0;
        java.lang.String _changeAddressONT_customerId = "";
        java.lang.String _changeAddressONT_customerAlias = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI _changeAddressONT_valuesHSI = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP _changeAddressONT_valuesVoIP = null;
        int _changeAddressONT_intCountIPTV = 0;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic _changeAddressONT_arrIPStatic = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic _changeAddressONT_arrIPDynamic = null;
        java.lang.String _changeAddressONT_latitude = "";
        java.lang.String _changeAddressONT_longitude = "";
        java.lang.String _changeAddressONT_mail = "";
        java.lang.String _changeAddressONT_zipCode = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _changeAddressONT__return = port.changeAddressONT(_changeAddressONT_login, _changeAddressONT_arrNewAddressONT, _changeAddressONT_idPackage, _changeAddressONT_customerId, _changeAddressONT_customerAlias, _changeAddressONT_valuesHSI, _changeAddressONT_valuesVoIP, _changeAddressONT_intCountIPTV, _changeAddressONT_arrIPStatic, _changeAddressONT_arrIPDynamic, _changeAddressONT_latitude, _changeAddressONT_longitude, _changeAddressONT_mail, _changeAddressONT_zipCode);
        System.out.println("changeAddressONT.result=" + _changeAddressONT__return);


        }
        {
        System.out.println("Invoking getVendor...");
        java.lang.String _getVendor_sn = "";
            com.totaplay.searchONT.tprovisioningSoa.NewVendor _getVendor__return = port.getVendor(_getVendor_sn);
        System.out.println("getVendor.result=" + _getVendor__return);


        }
        {
        System.out.println("Invoking getDataATA...");
        java.lang.String _getDataATA_cuenta = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelATA _getDataATA__return = port.getDataATA(_getDataATA_cuenta);
        System.out.println("getDataATA.result=" + _getDataATA__return);


        }
        {
        System.out.println("Invoking quitRoutingDN...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _quitRoutingDN_login = null;
        java.lang.String _quitRoutingDN_strOLTName = "";
        java.lang.String _quitRoutingDN_customerId = "";
        java.lang.String _quitRoutingDN_strName = "";
        java.lang.String _quitRoutingDN_strSNONT = "";
        java.lang.String _quitRoutingDN_strFrame = "";
        java.lang.String _quitRoutingDN_strSlot = "";
        java.lang.String _quitRoutingDN_strPort = "";
        java.lang.String _quitRoutingDN_strONTID = "";
        java.lang.String _quitRoutingDN_strModeInvoke = "";
        long _quitRoutingDN_lngUserId = 0;
        java.lang.String _quitRoutingDN_strIpInvoke = "";
        boolean _quitRoutingDN_blnGuiNew = false;
        java.lang.String _quitRoutingDN_strdn = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _quitRoutingDN__return = port.quitRoutingDN(_quitRoutingDN_login, _quitRoutingDN_strOLTName, _quitRoutingDN_customerId, _quitRoutingDN_strName, _quitRoutingDN_strSNONT, _quitRoutingDN_strFrame, _quitRoutingDN_strSlot, _quitRoutingDN_strPort, _quitRoutingDN_strONTID, _quitRoutingDN_strModeInvoke, _quitRoutingDN_lngUserId, _quitRoutingDN_strIpInvoke, _quitRoutingDN_blnGuiNew, _quitRoutingDN_strdn);
        System.out.println("quitRoutingDN.result=" + _quitRoutingDN__return);


        }
        {
        System.out.println("Invoking getOlts...");
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetCatalogOlts _getOlts__return = port.getOlts();
        System.out.println("getOlts.result=" + _getOlts__return);


        }
        {
        System.out.println("Invoking packageActivationEnlace...");
            com.totaplay.searchONT.tprovisioningSoa.ArrActivation _packageActivationEnlace_arrActivation = null;
        long _packageActivationEnlace_idPackage = 0;
        java.lang.String _packageActivationEnlace_idCustomer = "";
        java.lang.String _packageActivationEnlace_customerName = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP _packageActivationEnlace_arrAddOnVoIP = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrAddons _packageActivationEnlace_arrAddon = null;
        boolean _packageActivationEnlace_blnGaoke = false;
        boolean _packageActivationEnlace_blnPreactivation = false;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV _packageActivationEnlace_arrAddOnIptv = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic _packageActivationEnlace_arrIPStatic = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI _packageActivationEnlace_addInHSFI = null;
        long _packageActivationEnlace_lngIDaddIP = 0;
        java.lang.String _packageActivationEnlace_latitude = "";
        java.lang.String _packageActivationEnlace_longitude = "";
        java.lang.String _packageActivationEnlace_mail = "";
        java.lang.String _packageActivationEnlace_zipCode = "";
        int _packageActivationEnlace_intcounttroncal = 0;
        java.lang.String _packageActivationEnlace_strparamtrunt = "";
        java.lang.String _packageActivationEnlace_strparamIPs = "";
        java.lang.String _packageActivationEnlace_strparamIPsDynamic = "";
        int _packageActivationEnlace_intCountCCTV = 0;
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _packageActivationEnlace__return = port.packageActivationEnlace(_packageActivationEnlace_arrActivation, _packageActivationEnlace_idPackage, _packageActivationEnlace_idCustomer, _packageActivationEnlace_customerName, _packageActivationEnlace_arrAddOnVoIP, _packageActivationEnlace_arrAddon, _packageActivationEnlace_blnGaoke, _packageActivationEnlace_blnPreactivation, _packageActivationEnlace_arrAddOnIptv, _packageActivationEnlace_arrIPStatic, _packageActivationEnlace_addInHSFI, _packageActivationEnlace_lngIDaddIP, _packageActivationEnlace_latitude, _packageActivationEnlace_longitude, _packageActivationEnlace_mail, _packageActivationEnlace_zipCode, _packageActivationEnlace_intcounttroncal, _packageActivationEnlace_strparamtrunt, _packageActivationEnlace_strparamIPs, _packageActivationEnlace_strparamIPsDynamic, _packageActivationEnlace_intCountCCTV);
        System.out.println("packageActivationEnlace.result=" + _packageActivationEnlace__return);


        }
        {
        System.out.println("Invoking eliminaUserAAA...");
        port.eliminaUserAAA();


        }
        {
        System.out.println("Invoking insertATA...");
        java.lang.String _insertATA_ataCuenta = "";
        java.lang.String _insertATA_ataSN = "";
        java.lang.String _insertATA_ataPOT = "";
        java.lang.String _insertATA_ataDN = "";
        java.lang.String _insertATA_ataSTATUS = "";
        java.lang.String _insertATA_ataDOMINIO = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _insertATA__return = port.insertATA(_insertATA_ataCuenta, _insertATA_ataSN, _insertATA_ataPOT, _insertATA_ataDN, _insertATA_ataSTATUS, _insertATA_ataDOMINIO);
        System.out.println("insertATA.result=" + _insertATA__return);


        }
        {
        System.out.println("Invoking createUserAAAReporte...");
        port.createUserAAAReporte();


        }
        {
        System.out.println("Invoking decript...");
        java.lang.String _decript_idModel = "";
        java.lang.String _decript__return = port.decript(_decript_idModel);
        System.out.println("decript.result=" + _decript__return);


        }
        {
        System.out.println("Invoking validateBd...");
        java.lang.String _validateBd_usr = "";
        java.lang.String _validateBd_test = "";
        java.lang.String _validateBd__return = port.validateBd(_validateBd_usr, _validateBd_test);
        System.out.println("validateBd.result=" + _validateBd__return);


        }
        {
        System.out.println("Invoking obtIDActivacion...");
        java.lang.String _obtIDActivacion_idcustomer = "";
            com.totaplay.searchONT.tprovisioningSoa.IDTransactionActivation _obtIDActivacion__return = port.obtIDActivacion(_obtIDActivacion_idcustomer);
        System.out.println("obtIDActivacion.result=" + _obtIDActivacion__return);


        }
        {
        System.out.println("Invoking deleteONTSync...");
        long _deleteONTSync_lngUserId = 0;
        java.lang.String _deleteONTSync_strpwd = "";
        java.lang.String _deleteONTSync_strSNONT = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResultCancelONT _deleteONTSync__return = port.deleteONTSync(_deleteONTSync_lngUserId, _deleteONTSync_strpwd, _deleteONTSync_strSNONT);
        System.out.println("deleteONTSync.result=" + _deleteONTSync__return);


        }
        {
        System.out.println("Invoking deleteATA...");
        java.lang.String _deleteATA_cuenta = "";
        java.lang.String _deleteATA_dn = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _deleteATA__return = port.deleteATA(_deleteATA_cuenta, _deleteATA_dn);
        System.out.println("deleteATA.result=" + _deleteATA__return);


        }
        {
        System.out.println("Invoking createDN...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _createDN_login = null;
        java.lang.String _createDN_strOLTName = "";
        java.lang.String _createDN_customerId = "";
        java.lang.String _createDN_strName = "";
        java.lang.String _createDN_strSNONT = "";
        java.lang.String _createDN_strFrame = "";
        java.lang.String _createDN_strSlot = "";
        java.lang.String _createDN_strPort = "";
        java.lang.String _createDN_strONTID = "";
        java.lang.String _createDN_strModeInvoke = "";
        long _createDN_lngUserId = 0;
        java.lang.String _createDN_strIpInvoke = "";
        boolean _createDN_blnGuiNew = false;
        java.lang.String _createDN_strdn = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _createDN__return = port.createDN(_createDN_login, _createDN_strOLTName, _createDN_customerId, _createDN_strName, _createDN_strSNONT, _createDN_strFrame, _createDN_strSlot, _createDN_strPort, _createDN_strONTID, _createDN_strModeInvoke, _createDN_lngUserId, _createDN_strIpInvoke, _createDN_blnGuiNew, _createDN_strdn);
        System.out.println("createDN.result=" + _createDN__return);


        }
        {
        System.out.println("Invoking packageActivation...");
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _packageActivation_login = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrActivation _packageActivation_arrActivation = null;
        long _packageActivation_idPackage = 0;
        java.lang.String _packageActivation_idCustomer = "";
        java.lang.String _packageActivation_customerAlias = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI _packageActivation_addInHSFI = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP _packageActivation_arrAddInVoIP = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV _packageActivation_addInIPTV = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrAddons _packageActivation_arrAddon = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic _packageActivation_arrIPStatic = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic _packageActivation_arrIPDynamic = null;
        java.lang.String _packageActivation_latitude = "";
        java.lang.String _packageActivation_longitude = "";
        java.lang.String _packageActivation_mail = "";
        java.lang.String _packageActivation_zipCode = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _packageActivation__return = port.packageActivation(_packageActivation_login, _packageActivation_arrActivation, _packageActivation_idPackage, _packageActivation_idCustomer, _packageActivation_customerAlias, _packageActivation_addInHSFI, _packageActivation_arrAddInVoIP, _packageActivation_addInIPTV, _packageActivation_arrAddon, _packageActivation_arrIPStatic, _packageActivation_arrIPDynamic, _packageActivation_latitude, _packageActivation_longitude, _packageActivation_mail, _packageActivation_zipCode);
        System.out.println("packageActivation.result=" + _packageActivation__return);


        }
        {
        System.out.println("Invoking activacionConsultaDatos...");
        java.lang.String _activacionConsultaDatos_strvalue = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfModelGetONT _activacionConsultaDatos__return = port.activacionConsultaDatos(_activacionConsultaDatos_strvalue);
        System.out.println("activacionConsultaDatos.result=" + _activacionConsultaDatos__return);


        }
        {
        System.out.println("Invoking packageActivationFusion...");
            com.totaplay.searchONT.tprovisioningSoa.ArrBrm _packageActivationFusion_arrBrm = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrLogin _packageActivationFusion_login = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrActivation _packageActivationFusion_arrActivation = null;
        long _packageActivationFusion_idPackage = 0;
        java.lang.String _packageActivationFusion_idCustomer = "";
        java.lang.String _packageActivationFusion_customerAlias = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrAddOnHSFI _packageActivationFusion_addInHSFI = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnVoIP _packageActivationFusion_arrAddInVoIP = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrayOfArrAddOnIPTV _packageActivationFusion_addInIPTV = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrAddons _packageActivationFusion_arrAddon = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPStatic _packageActivationFusion_arrIPStatic = null;
            com.totaplay.searchONT.tprovisioningSoa.ArrIPDynamic _packageActivationFusion_arrIPDynamic = null;
        java.lang.String _packageActivationFusion_latitude = "";
        java.lang.String _packageActivationFusion_longitude = "";
        java.lang.String _packageActivationFusion_mail = "";
        java.lang.String _packageActivationFusion_zipCode = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResult _packageActivationFusion__return = port.packageActivationFusion(_packageActivationFusion_arrBrm, _packageActivationFusion_login, _packageActivationFusion_arrActivation, _packageActivationFusion_idPackage, _packageActivationFusion_idCustomer, _packageActivationFusion_customerAlias, _packageActivationFusion_addInHSFI, _packageActivationFusion_arrAddInVoIP, _packageActivationFusion_addInIPTV, _packageActivationFusion_arrAddon, _packageActivationFusion_arrIPStatic, _packageActivationFusion_arrIPDynamic, _packageActivationFusion_latitude, _packageActivationFusion_longitude, _packageActivationFusion_mail, _packageActivationFusion_zipCode);
        System.out.println("packageActivationFusion.result=" + _packageActivationFusion__return);


        }
        {
        System.out.println("Invoking getIPWANTR069...");
        java.lang.String _getIPWANTR069_strSN = "";
            com.totaplay.searchONT.tprovisioningSoa.ArrResIPWAN _getIPWANTR069__return = port.getIPWANTR069(_getIPWANTR069_strSN);
        System.out.println("getIPWANTR069.result=" + _getIPWANTR069__return);


        }

        System.exit(0);
    }

}
